#!/usr/bin/env bash
#
# D4-B manufacturing provisioning for device enrollment.
#
# Builds an NVS image that holds the enroll *factory identity* (and optional
# WiFi credentials + enroll server URL) and flashes it to the 'nvs' partition
# of an ESP32. This is done ONCE at manufacturing: the identity is
# intentionally NOT part of the firmware/release image.
#
# Entries written into NVS namespace 'enroll':
#   ca_crt     = ManagementCA.crt        (server CA the device trusts)
#   fact_crt   = device-factory.crt      (shared factory client cert)
#   fact_key   = device-factory.key      (shared factory client key)
#   server_url = enroll server URL       (only if ENROLL_URL is set)
# and, if WIFI_SSID/WIFI_PWD are set, into namespace 'wifi':
#   ssid/pwd   = WiFi credentials (read by AppWifi at boot)
#
# The PEM files come from the ch06-servers repo keys/ (generated by
# scripts/35-issue-enroll-certs.sh there).
#
# Usage:
#   WIFI_SSID=mywifi WIFI_PWD=secret ENROLL_URL=https://192.168.1.100:9443/enroll \
#     KEYS_DIR=/path/to/servers/keys PORT=/dev/ttyUSB0 bash scripts/factory-nvs.sh
#
# The nvs partition offset/size are taken from scripts/flash-layout.sh
# (which reads partitions.txt + build/flasher_args.json) - no magic numbers.
#
# Env:
#   KEYS_DIR    dir with ManagementCA.crt / device-factory.crt / device-factory.key
#   WIFI_SSID   optional: WiFi network name to provision (no quotes)
#   WIFI_PWD    optional: WiFi password to provision (no quotes)
#   ENROLL_URL  optional: enroll server URL, e.g. https://192.168.1.100:9443/enroll
#   NVS_OFFSET  optional: override nvs partition offset (default from flash-layout.sh)
#   NVS_SIZE    optional: override nvs partition size   (default from flash-layout.sh)
#   BLINKY_DIR  blinky project dir (for the layout; default sibling of scripts/)
#   PORT        serial port for flashing (default /dev/ttyUSB0)
#   FLASH=1     also flash after generating
#
# NOTE: writing an NVS image REPLACES the whole nvs partition. Do this before
# first boot / before the app stores runtime state (device key + cert). Re-
# provisioning later wipes the device key/cert and forces re-enrollment.

set -euo pipefail

# Shared config/helpers (SCRIPT_DIR/ROOT_DIR/BLINKY_DIR, .env load, tooling).
# shellcheck disable=SC1091
. "$(dirname "${BASH_SOURCE[0]}")/factory-common.sh"

# nvs offset/size come from the authoritative flash layout (no magic numbers).
load_flash_layout

KEYS_DIR="${KEYS_DIR:-$ROOT_DIR/keys}"
NVS_OFFSET="${NVS_OFFSET:-${FLASH_NVS_OFFSET:-0x9000}}"
NVS_SIZE="${NVS_SIZE:-${FLASH_NVS_SIZE:-0x5000}}"
PORT="${PORT:-/dev/ttyUSB0}"
OUT="${1:-factory-nvs.bin}"
PYTHON="${PYTHON:-python3}"
FLASH="${FLASH:-0}"

for f in ManagementCA.crt device-factory.crt device-factory.key; do
  [[ -s "$KEYS_DIR/$f" ]] || { echo "error: missing $KEYS_DIR/$f" >&2; exit 1; }
done

# --- locate the ESP-IDF NVS partition generator ---------------------------
GEN="${NVS_PART_GEN:-}"
if [[ -z "$GEN" ]]; then
  if [[ -n "${IDF_PATH:-}" && -f "$IDF_PATH/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py" ]]; then
    GEN="$IDF_PATH/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py"
  elif command -v nvs_partition_gen.py >/dev/null 2>&1; then
    GEN="$(command -v nvs_partition_gen.py)"
  else
    echo "error: nvs_partition_gen.py not found. Source ESP-IDF (export.sh) or set NVS_PART_GEN." >&2
    exit 1
  fi
fi

CSV="$(mktemp --suffix=.csv)"
trap 'rm -f "$CSV"' EXIT

# --- build the generator CSV (values read from the PEM files) -------------
"$PYTHON" - "$KEYS_DIR" "$CSV" <<'PY'
import csv, os, sys
keys_dir, csv_path = sys.argv[1], sys.argv[2]

def pem(name):
    with open(f"{keys_dir}/{name}", "r") as f:
        return f.read()

def clean(v):
    v = (v or "").strip()
    return v[1:-1] if len(v) >= 2 and v[0] == v[-1] == '"' else v

wifi_ssid = clean(os.environ.get("WIFI_SSID", ""))
wifi_pwd  = clean(os.environ.get("WIFI_PWD", ""))
enroll_url = clean(os.environ.get("ENROLL_URL", ""))

with open(csv_path, "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["key", "type", "encoding", "value"])
    w.writerow(["enroll", "namespace", "", ""])
    w.writerow(["ca_crt",   "data", "string", pem("ManagementCA.crt")])
    w.writerow(["fact_crt", "data", "string", pem("device-factory.crt")])
    w.writerow(["fact_key", "data", "string", pem("device-factory.key")])
    if enroll_url:
        w.writerow(["server_url", "data", "string", enroll_url])
    if wifi_ssid and wifi_pwd:
        w.writerow(["wifi", "namespace", "", ""])
        w.writerow(["ssid", "data", "string", wifi_ssid])
        w.writerow(["pwd",  "data", "string", wifi_pwd])
print(f"wrote {csv_path}")
print(f"enroll URL included: {'yes' if enroll_url else 'no'}")
print(f"wifi credentials:    {'yes' if wifi_ssid and wifi_pwd else 'no'}")
print("NOTE: firmware reads these from NVS only - there is no compile-time fallback.")
PY

# --- generate the NVS image ------------------------------------------------
"$PYTHON" "$GEN" generate "$CSV" "$OUT" "$NVS_SIZE"
echo "Generated $OUT ($(stat -c%s "$OUT") bytes) for nvs partition @ $NVS_OFFSET"

if [[ "$FLASH" == "1" ]]; then
  esp_tool --chip esp32 -p "$PORT" -b 460800 --before default-reset --after no-reset \
    write-flash "$NVS_OFFSET" "$OUT"
else
  echo
  echo "Flash it manually (do this BEFORE first boot):"
  echo "  esp_tool write-flash $NVS_OFFSET $OUT   (offset from scripts/flash-layout.sh)"
fi
